### ISSUE TITLE
Error when calling animore()

### ISSUE THREAD

**Issue by fantasia949** [GianlucaGuarini/animore#2]
When calling animore(), I got a reference error:

``` javascript
function create(el, opts = {}) {
  const animore = bind( // <-------------------- const  animore may be the issue
    Object.assign({}, ANIMORE_STRUCT, {
      el,
      opts:  bind(
        Object.assign(
          {},
          DEFAULT_OPTIONS,
          opts
        ),
        ['onStart', 'onEnd', 'onCancel'],
        animore // <--------------------animore is undefined here
      ),
      props: {
        old: null,
        new: null
      }
    }),
    ['clear', 'stash', 'apply']
  )
  return Object.seal(animore)
}
```
It seems the imported module is from '/lib/index.js' instead of '/animore.js' for unknown reason. When I try the main entry, the app works fine. I guess the problem may come from the ```const animore ``` declaration. A smart editor should complain when you use const in this case.

**Comment by GianlucaGuarini** [comment]
@fantasia949 thanks for reporting it. The issue was fixed in animore@2.0.2
